var charity = {
"type": "FeatureCollection",
"name": "charitable_snap",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "CompanyName": "Bishops' Storehouse", "Address": "2295 Ringwood Ave ", "City": "San Jose", "State": "CA", "ZIPCode": "95131", "MondayOpen": "Closed", "MondayClose": "Closed", "TuesdayOpen": "830", "TuesdayClose": "1230", "WednesdayOpen": "1030", "WednesdayClose": "1430", "ThursdayOpen": "Closed", "ThursdayClose": "Closed", "FridayOpen": "Closed", "FridayClose": "Closed", "SaturdayOpen": "0830", "SaturdayClose": "1230", "SundayOpen": "Closed", "SundayClose": "Closed", "accepts_snap": 0.0, "Type": "charitable" }, "geometry": { "type": "Point", "coordinates": [ -121.899948, 37.40194 ] } },
{ "type": "Feature", "properties": { "CompanyName": "Loaves & Fishes Family Kitchen", "Address": "1500 Berger Dr", "City": "San Jose", "State": "CA", "ZIPCode": "95112", "MondayOpen": "0900", "MondayClose": "1600", "TuesdayOpen": "900", "TuesdayClose": "1600", "WednesdayOpen": "900", "WednesdayClose": "1600", "ThursdayOpen": "0900", "ThursdayClose": "1600", "FridayOpen": "0900", "FridayClose": "1600", "SaturdayOpen": "Closed", "SaturdayClose": "Closed", "SundayOpen": "Closed", "SundayClose": "Closed", "accepts_snap": 0.0, "Type": "charitable" }, "geometry": { "type": "Point", "coordinates": [ -121.897025, 37.37089 ] } },
{ "type": "Feature", "properties": { "CompanyName": "Second Harvest-Silicon Vly", "Address": "4001 N 1st St", "City": "San Jose", "State": "CA", "ZIPCode": "95134", "MondayOpen": "0800", "MondayClose": "1700", "TuesdayOpen": "800", "TuesdayClose": "1700", "WednesdayOpen": "800", "WednesdayClose": "1700", "ThursdayOpen": "0800", "ThursdayClose": "1700", "FridayOpen": "0800", "FridayClose": "1700", "SaturdayOpen": "Closed", "SaturdayClose": "Closed", "SundayOpen": "Closed", "SundayClose": "Closed", "accepts_snap": 0.0, "Type": "charitable" }, "geometry": { "type": "Point", "coordinates": [ -121.952612, 37.413249 ] } },
{ "type": "Feature", "properties": { "CompanyName": "Choicelunch", "Address": "1615 Remuda Lane", "City": "San Jose", "State": "CA", "ZIPCode": "95112", "MondayOpen": null, "MondayClose": null, "TuesdayOpen": null, "TuesdayClose": null, "WednesdayOpen": null, "WednesdayClose": null, "ThursdayOpen": null, "ThursdayClose": null, "FridayOpen": null, "FridayClose": null, "SaturdayOpen": null, "SaturdayClose": null, "SundayOpen": null, "SundayClose": null, "accepts_snap": 0.0, "Type": "charitable" }, "geometry": { "type": "Point", "coordinates": [ -121.908712, 37.3720775 ] } },
{ "type": "Feature", "properties": { "CompanyName": "Saint Victor Food Pantry", "Address": "3150 Sierra Road", "City": "San Jose", "State": "CA", "ZIPCode": "95132", "MondayOpen": null, "MondayClose": null, "TuesdayOpen": null, "TuesdayClose": null, "WednesdayOpen": null, "WednesdayClose": null, "ThursdayOpen": null, "ThursdayClose": null, "FridayOpen": null, "FridayClose": null, "SaturdayOpen": null, "SaturdayClose": null, "SundayOpen": null, "SundayClose": null, "accepts_snap": 0.0, "Type": "charitable" }, "geometry": { "type": "Point", "coordinates": [ -121.8509995, 37.3968915 ] } },
{ "type": "Feature", "properties": { "CompanyName": "San Jose Unified School District Nutrition Services", "Address": "2222 Unified Way", "City": "San Jose", "State": "CA", "ZIPCode": "95125", "MondayOpen": null, "MondayClose": null, "TuesdayOpen": null, "TuesdayClose": null, "WednesdayOpen": null, "WednesdayClose": null, "ThursdayOpen": null, "ThursdayClose": null, "FridayOpen": null, "FridayClose": null, "SaturdayOpen": null, "SaturdayClose": null, "SundayOpen": null, "SundayClose": null, "accepts_snap": 0.0, "Type": "charitable" }, "geometry": { "type": "Point", "coordinates": [ -121.8726693, 37.2964929 ] } },
{ "type": "Feature", "properties": { "CompanyName": "CCC Food Pantry", "Address": "990 South Capitol Avenue", "City": "San Jose", "State": "CA", "ZIPCode": "95127", "MondayOpen": null, "MondayClose": null, "TuesdayOpen": null, "TuesdayClose": null, "WednesdayOpen": null, "WednesdayClose": null, "ThursdayOpen": null, "ThursdayClose": null, "FridayOpen": null, "FridayClose": null, "SaturdayOpen": null, "SaturdayClose": null, "SundayOpen": null, "SundayClose": null, "accepts_snap": 0.0, "Type": "charitable" }, "geometry": { "type": "Point", "coordinates": [ -121.8268231, 37.3522032 ] } }
]
};
